const fa = [
  {
    soundNum: "1",
    sound: "001_somtimesiam_defhi.mp3",
    text: "بعضی وقت‌ها",
    synonym: "با بقیه فرق دارم",
  },
  {
    soundNum: "2",
    sound: "002_somtimesiam_norm.mp3",
    text: "بعضی وقت‌ها",
    synonym: "نادیده گرفته میشم",
  },
  {
    soundNum: "3",
    sound: "003_somtimesiam_weary.mp3",
    text: "بعضی وقت‌ها",
    synonym: "نابودم",
  },
  {
    soundNum: "4",
    sound: "004_somtimesiamhig_wonder.mp3",
    text: "بعضی وقت‌ها",
    synonym: "سردرگمم",
  },
  {
    soundNum: "5",
    sound: "005_somtimesiam_mix.mp3",
    text: "بعضی وقت‌ها",
    synonym: "تنهام",
  },
  {
    soundNum: "6",
    sound: "006_we_mix.mp3",
    text: "ما",
    synonym: "نادیده گرفته میشیم",
  },
  {
    soundNum: "7",
    sound: "007_they_mix.mp3",
    text: "اونا",
    synonym: "فراموش میشند",
  },
  {
    soundNum: "8",
    sound: "008_they_accuse.mp3",
    text: "اونا",
    synonym: "با بقیه فرق دارند",
  },
  {
    soundNum: "9",
    sound: "009_they_accuse.mp3",
    text: "اونا",
    synonym: "متفاوتند",
  },
  {
    soundNum: "10",
    sound: "010_wecan_mix.mp3",
    text: "می‌تونیم",
    synonym: "موفق بشیم",
  },
  {
    soundNum: "11",
    sound: "011_wecan_groupmix.mp3",
    text: "می‌تونیم",
    synonym: "از پسش بربیایم",
  },
  {
    soundNum: "12",
    sound: "012_theycan_solo.mp3",
    text: "می‌تونند",
    synonym: "تظاهر کنند",
  },
  {
    soundNum: "13",
    sound: "013_theycan_low.mp3",
    text: "می‌تونند",
    synonym: "موفق بشند",
  },
  {
    soundNum: "14",
    sound: "014_theycan_def.mp3",
    text: "می‌تونند",
    synonym: "من رو ببیند",
  },
  {
    soundNum: "15",
    sound: "015_theycan_mix.mp3",
    text: "می‌تونند",
    synonym: "تغییر کنند",
  },
  {
    soundNum: "16",
    sound: "016_theycan_weary.mp3",
    text: "می‌تونند",
    synonym: "جای من باشند",
  },
  {
    soundNum: "17",
    sound: "017_theycan_accusemix.mp3",
    text: "می‌تونند",
    synonym: "کاری کنند",
  },
  {
    soundNum: "18",
    sound: "018_wecant_mix.mp3",
    text: "نمی‌تونیم",
    synonym: "ساکت باشیم",
  },
  {
    soundNum: "19",
    sound: "019_wecant_despair.mp3",
    text: "نمی‌تونیم",
    synonym: "آزاد بشیم",
  },
  {
    soundNum: "20",
    sound: "020_you_twin.mp3",
    text: "تو",
    synonym: "غریبی",
  },
  {
    soundNum: "21",
    sound: "021_you_mix.mp3",
    text: "شما",
    synonym: "با بقیه فرق دارید",
  },
  {
    soundNum: "22",
    sound: "022_you_solo.mp3",
    text: "شما",
    synonym: "دیده نمیشید",
  },
  {
    soundNum: "23",
    sound: "023_you_ss.mp3",
    text: "تو",
    synonym: "قوی هستی",
  },
  {
    soundNum: "24",
    sound: "024_beyou_ssmix.mp3",
    text: "خودت باش",
    synonym: "بااراده",
  },
  {
    soundNum: "25",
    sound: "025_beyou_accusemix.mp3",
    text: "خودت باش",
    synonym: "قوی",
  },
  {
    soundNum: "26",
    sound: "026_bethem_ssmix.mp3",
    text: "درک کن",
    synonym: "تنهایند",
  },
  {
    soundNum: "27",
    sound: "027_bethem_mix.mp3",
    text: "درک کن",
    synonym: "نادیده گرفته شدند",
  },
  {
    soundNum: "28",
    sound: "028_invisible_mix.mp3",
    text: "نادیده گرفته میشند",
    synonym: "تنهایند",
  },
  {
    soundNum: "29",
    sound: "029_invisible_resmix.mp3",
    text: "نادیده گرفته میشم",
    synonym: "ناراحتم",
  },
  {
    soundNum: "30",
    sound: "030_invisible_wearymix.mp3",
    text: "نادیده گرفته میشم",
    synonym: "تنهام",
  },
  {
    soundNum: "31",
    sound: "031_invisible_dreammix.mp3",
    text: "نادیده گرفته میشم",
    synonym: "غریبم",
  },
  {
    soundNum: "32",
    sound: "032_invisible_dreamsolo.mp3",
    text: "نادیده گرفته میشم",
    synonym: "نابودم",
  },
  {
    soundNum: "33",
    sound: "033_invisible_concern.mp3",
    text: "نادیده گرفته میشیم",
    synonym: "اصلا نیستیم",
  },
  {
    soundNum: "34",
    sound: "034_invisible_concernmix.mp3",
    text: "نادیده گرفته میشیم",
    synonym: "فراموش میشیم",
  },
  {
    soundNum: "35",
    sound: "035_invisible_small.mp3",
    text: "نادیده گرفته میشیم",
    synonym: "شنیده نمیشیم",
  },
  {
    soundNum: "36",
    sound: "036_invisible_accusemix.mp3",
    text: "نادیده گرفته میشید",
    synonym: "تنهایید",
  },
  {
    soundNum: "37",
    sound: "037_seethem_ss.mp3",
    text: "ببین اونارو",
    synonym: "خودت رو جای اونا بذار",
  },
  {
    soundNum: "38",
    sound: "038_seethem_accusemix.mp3",
    text: "ببینید اونارو",
    synonym: "دارند می‌جنگند",
  },
  {
    soundNum: "39",
    sound: "039_seeme_ssmix.mp3",
    text: "منو ببین",
    synonym: "دور افتاده‌ام",
  },
  {
    soundNum: "40",
    sound: "040_seeme_accusemix.mp3",
    text: "منو ببینید",
    synonym: "محکمم",
  },
  {
    soundNum: "41",
    sound: "041_sometimesiam_beatmix.mp3",
    text: "بعضی وقت‌ها",
    synonym: "سردرگمم",
  },
  {
    soundNum: "42",
    sound: "042_sometimesiam_mix.mp3",
    text: "بعضی وقت‌ها",
    synonym: "آزادم",
  },
  {
    soundNum: "43",
    sound: "043_seeyourself_mix.mp3",
    text: "خودتو ببین",
    synonym: "قوی",
  },
  {
    soundNum: "44",
    sound: "044_seeyou_I.mp3",
    text: "شما رو ‌می‌بینم",
    synonym: "تسلیم نشید",
  },
  {
    soundNum: "45",
    sound: "045_seeyou_solo.mp3",
    text: "شما رو ‌می‌بینم",
    synonym: "ناراحتید",
  },
  {
    soundNum: "46",
    sound: "046_seeyou_mix.mp3",
    text: "شما رو ‌می‌بینم",
    synonym: "قوی بمونید",
  },
  {
    soundNum: "47",
    sound: "047_they_ssmix.mp3",
    text: "اونا",
    synonym: "نادیده گرفته میشند",
  },
  {
    soundNum: "48",
    sound: "048_they_ssmix.mp3",
    text: "اونا",
    synonym: "سردرگم‌اند",
  },
  {
    soundNum: "49",
    sound: "049_they_triple.mp3",
    text: "اونا",
    synonym: "فراموش میشند",
  },
  {
    soundNum: "50",
    sound: "050_they_accusemix.mp3",
    text: "اونا",
    synonym: "با بقیه فرق دارند",
  },
  {
    soundNum: "51",
    sound: "051_seethem_command.mp3",
    text: "ببین اونارو",
    synonym: "تنهایند",
  },
  {
    soundNum: "52",
    sound: "052_seethem_commandmix.mp3",
    text: "ببین اونارو",
    synonym: "آزادند",
  },
  {
    soundNum: "53",
    sound: "053_seethem_broadcast.mp3",
    text: "ببین اونارو",
    synonym: "تسلیم نمیشند",
  },
  {
    soundNum: "54",
    sound: "054_seethem_solo.mp3",
    text: "ببین اونارو",
    synonym: "ناراحت‌اند",
  },
  {
    soundNum: "55",
    sound: "055_youcant_mix.mp3",
    text: "نمی‌تونی",
    synonym: "از پسش بربیای",
  },
  {
    soundNum: "56",
    sound: "056_youcant_solo.mp3",
    text: "نمی‌تونی",
    synonym: "تظاهر کنی",
  },
  {
    soundNum: "57",
    sound: "057_youcant_mix.mp3",
    text: "نمی‌تونی",
    synonym: "منو متوقف کنی",
  },
  {
    soundNum: "58",
    sound: "058_theycant_mix.mp3",
    text: "نمی‌تونند",
    synonym: "منو متوقف کنند",
  },
  {
    soundNum: "59",
    sound: "059_theycant_threat.mp3",
    text: "نمی‌تونند",
    synonym: "منو تغییر بدهند",
  },
  {
    soundNum: "60",
    sound: "060_I_confident.mp3",
    text: "من",
    synonym: "آزادم",
  },
  {
    soundNum: "61",
    sound: "061_I_mix.mp3",
    text: "من",
    synonym: "قوی‌ام",
  },
  {
    soundNum: "62",
    sound: "062_I_mix.mp3",
    text: "من",
    synonym: "می‌جنگم",
  },
  {
    soundNum: "63",
    sound: "063_youcant_seeme.mp3",
    text: "نمی‌بینی",
    synonym: "تنهام",
  },
  {
    soundNum: "64",
    sound: "064_youcant_mix.mp3",
    text: "نمی‌بینی",
    synonym: "امید دارم",
  },
  {
    soundNum: "65",
    sound: "065_I_familymix.mp3",
    text: "من",
    synonym: "محکم‌ام",
  },
  {
    soundNum: "66",
    sound: "066_i_chant.mp3",
    text: "من",
    synonym: "می‌توانم",
  },
  {
    soundNum: "67",
    sound: "067_i_doublemix.mp3",
    text: "من",
    synonym: "نگرانم",
  },
  {
    soundNum: "68",
    sound: "068_seethem_chant.mp3",
    text: "ببینید",
    synonym: "تسلیم نمیشند",
  },
  {
    soundNum: "69",
    sound: "069_you_probmix.mp3",
    text: "تو",
    synonym: "منو ببین",
  },
  {
    soundNum: "70",
    sound: "070_nobodyseesme_mix.mp3",
    text: "منو درک نمی‌کنند",
    synonym: "تنهام",
  },
  {
    soundNum: "71",
    sound: "071_nobodyseesme_mix.mp3",
    text: "منو درک نمی‌کنند",
    synonym: "دیده نمیشم",
  },
  {
    soundNum: "72",
    sound: "072_beme_sadmix.mp3",
    text: "من باش",
    synonym: "منو ببین",
  },
  {
    soundNum: "73",
    sound: "073_beme_daremix.mp3",
    text: "من باش",
    synonym: "نگرانم",
  },
  {
    soundNum: "74",
    sound: "074_beme_solo.mp3",
    text: "من باش",
    synonym: "با بقیه فرق دارم",
  },
]

export default fa
