const it = [
  {
    soundNum: "1",
    sound: "001-II-Sometimes-I-Am-solo-Hi.mp3",
    text: "a volte io sono",
    synonym: "diversa",
  },
  {
    soundNum: "2",
    sound: "002-II-Sometimes-I-Am-solo-Lo.mp3",
    text: "a volte io sono",
    synonym: "diverso",
  },
  {
    soundNum: "3",
    sound: "003-II-Sometimes-I-Am-solo-Reg.mp3",
    text: "a volte io sono",
    synonym: "invisibile",
  },
  {
    soundNum: "4",
    sound: "004-II-Sometimes-I-Am-Multi-Mix.mp3",
    text: "a volte io sono",
    synonym: "nascosta",
  },
  {
    soundNum: "5",
    sound: "005-II-Sometimes-I-Am-Definite-Solo-Reg.mp3",
    text: "a volte io sono",
    synonym: "eclissata",
  },
  {
    soundNum: "6",
    sound: "006-II-We-Are-Mix.mp3",
    text: "noi siamo",
    synonym: "sole",
  },
  {
    soundNum: "7",
    sound: "007-II-We-Are-Hi.mp3",
    text: "noi siamo",
    synonym: "perse",
  },
  {
    soundNum: "8",
    sound: "008-II-They-Are-Definite.mp3",
    text: "loro sono",
    synonym: "invisibili",
  },
  {
    soundNum: "9",
    sound: "009-II-They-Are-Definite-Hi.mp3",
    text: "loro sono",
    synonym: "altrove",
  },
  {
    soundNum: "10",
    sound: "010-II-They-Are-Definite-Lo-Slo.mp3",
    text: "loro sono",
    synonym: "distanti",
  },
  {
    soundNum: "11",
    sound: "011-II-They-Are-Definite-Mix.mp3",
    text: "loro sono",
    synonym: "inesistenti",
  },
  {
    soundNum: "12",
    sound: "012-II-We-Can-Hi.mp3",
    text: "noi possiamo",
    synonym: "fingere",
  },
  {
    soundNum: "13",
    sound: "013-II-We-Can-Definite-Reg.mp3",
    text: "noi possiamo",
    synonym: "loro non possono",
  },
  {
    soundNum: "14",
    sound: "014-II-We-Can-Lo-Slo.mp3",
    text: "noi possiamo",
    synonym: "scomparire",
  },
  {
    soundNum: "15",
    sound: "015-II-They-Can-Reg.mp3",
    text: "loro possono",
    synonym: "fingere",
  },
  {
    soundNum: "16",
    sound: "016-II-They-Can-Mix.mp3",
    text: "loro possono",
    synonym: "noi non possiamo",
  },
  {
    soundNum: "17",
    sound: "017-II-They-Can-Dismissive.mp3",
    text: "loro possono",
    synonym: "",
  },
  {
    soundNum: "18",
    sound: "018-II-We-Cant-Reg.mp3",
    text: "noi non possiamo",
    synonym: "scomparire",
  },
  {
    soundNum: "19",
    sound: "019-We-Cant-Hi-Lo-Mix.mp3",
    text: "noi non possiamo",
    synonym: "tutto",
  },
  {
    soundNum: "20",
    sound: "020-II-You-Are-Reg.mp3",
    text: "tu sei",
    synonym: "assente",
  },
  {
    soundNum: "21",
    sound: "021-II-You-Are-Singsong.mp3",
    text: "tu sei",
    synonym: "piccolo",
  },
  {
    soundNum: "22",
    sound: "022-II-You-Are-Accuse.mp3",
    text: "tu sei",
    synonym: "libera",
  },
  {
    soundNum: "23",
    sound: "023-II-Be-Them-2-Ways-Mix.mp3",
    text: "essere loro",
    synonym: "essere me",
  },
  {
    soundNum: "24",
    sound: "024-II-Be-Them-Lo-Slo.mp3",
    text: "essere loro",
    synonym: "noi non possiamo",
  },
  {
    soundNum: "25",
    sound: "025-II-Be-Them-Query-Reg.mp3",
    text: "sii loro",
    synonym: "sii me",
  },
  {
    soundNum: "26",
    sound: "026-II-Invisible-Hi.mp3",
    text: "Invisibile",
    synonym: "nascosto",
  },
  {
    soundNum: "27",
    sound: "027-II-Invisible-Lo.mp3",
    text: "invisibile",
    synonym: "",
  },
  {
    soundNum: "28",
    sound: "028-II-Invisible-Reg.mp3",
    text: "",
    synonym: "dolore",
  },
  {
    soundNum: "29",
    sound: "029-II-Invisible-Syllable-Multi-Bot-Mix.mp3",
    text: "invisibile",
    synonym: "distanti",
  },
  {
    soundNum: "30",
    sound: "030-II-Invisible-Fast-Breath-Reg.mp3",
    text: "invisibile",
    synonym: "perse",
  },
  {
    soundNum: "31",
    sound: "031-II-Invisible-Sad-Dbl.mp3",
    text: "invisibile",
    synonym: "altrove",
  },
  {
    soundNum: "32",
    sound: "032-II-See-Them-Hi.mp3",
    text: "vederle",
    synonym: "vederti",
  },
  {
    soundNum: "33",
    sound: "033-II-See-Them-Lo-Slo.mp3",
    text: "vederli",
    synonym: "guardali",
  },
  {
    soundNum: "34",
    sound: "034-II-See-Them-Command-Lo.mp3",
    text: "guardali",
    synonym: "invisibili",
  },
  {
    soundNum: "35",
    sound: "035-II-See-Me-Overlap.mp3",
    text: "vedermi",
    synonym: "impaurito",
  },
  {
    soundNum: "36",
    sound: "036-II-See-Me-Plaintive-Hi.mp3",
    text: "guardami",
    synonym: "vederti",
  },
  {
    soundNum: "37",
    sound: "037-II-See-Me-Plaintive-Lo.mp3",
    text: "guardami",
    synonym: "forte",
  },
  {
    soundNum: "38",
    sound: "038-II-Sometimes-I-Am-Hi-Query.mp3",
    text: "a volte io sono",
    synonym: "solo",
  },
  {
    soundNum: "39",
    sound: "039-II-Sometimes-I-Am-Lo-Query.mp3",
    text: "a volte io sono",
    synonym: "inesistente",
  },
  {
    soundNum: "40",
    sound: "040-II-Sometimes-I-Am-Mix.mp3",
    text: "a volte io sono",
    synonym: "visibile",
  },
  {
    soundNum: "41",
    sound: "041-II-See-You-Overlap.mp3",
    text: "vederti",
    synonym: "vederli",
  },
  {
    soundNum: "42",
    sound: "042-II-See-You-Accuse-Lo.mp3",
    text: "guardati",
    synonym: "guardami",
  },
  {
    soundNum: "43",
    sound: "043-II-They-Are-Reg.mp3",
    text: "loro sono",
    synonym: "lontani",
  },
  {
    soundNum: "44",
    sound: "044-II-They-Are-Mix.mp3",
    text: "loro sono",
    synonym: "tristi",
  },
  {
    soundNum: "45",
    sound: "045-II-They-Are-Hi.mp3",
    text: "loro sono",
    synonym: "contente",
  },
  {
    soundNum: "46",
    sound: "046-II-See-Them-Decline-Mix.mp3",
    text: "vederle",
    synonym: "guardale",
  },
  {
    soundNum: "47",
    sound: "047-II-See-Them-All-Mix.mp3",
    text: "guardali",
    synonym: "scomparire",
  },
  {
    soundNum: "48",
    sound: "048-II-You-Cant-Tri-Overlap.mp3",
    text: "tu non puoi",
    synonym: "esistere",
  },
  {
    soundNum: "49",
    sound: "049-II-You-Cant-Hopeless-Solo.mp3",
    text: "tu non puoi",
    synonym: "vedermi",
  },
  {
    soundNum: "50",
    sound: "050-II-They-Cant-Hi-Slo.mp3",
    text: "loro non possono",
    synonym: "fingere",
  },
  {
    soundNum: "51",
    sound: "051-II-They-Cant-Trio-Mix.mp3",
    text: "loro non possono",
    synonym: "",
  },
  {
    soundNum: "52",
    sound: "052-II-They-Cant-Definite-Solo-Reg.mp3",
    text: "loro non possono",
    synonym: "avere paura",
  },
  {
    soundNum: "53",
    sound: "053-II-They-Cant-Definite-Mix.mp3",
    text: "loro non possono",
    synonym: "",
  },
  {
    soundNum: "54",
    sound: "054-II-I-Am-Reg-Solo-Assured.mp3",
    text: "io sono",
    synonym: "libero",
  },
  {
    soundNum: "55",
    sound: "055-II-I-Am-Trio.mp3",
    text: "io sono",
    synonym: "",
  },
  {
    soundNum: "56",
    sound: "056-II-I-Am-Mixed-Feelings.mp3",
    text: "io sono",
    synonym: "tu sei",
  },
  {
    soundNum: "57",
    sound: "057-II-You-Cant-See-Me-Mix.mp3",
    text: "tu non puoi vedermi",
    synonym: "invisibile",
  },
  {
    soundNum: "58",
    sound: "058-II-You-Cant-See-Finger-Point-Solo-Reg.mp3",
    text: "",
    synonym: "guardami",
  },
  {
    soundNum: "59",
    sound: "059-II-You-Cant-See-Me-I-Mean-You-Mix.mp3",
    text: "tu non puoi vedermi",
    synonym: "nascosto",
  },
  {
    soundNum: "60",
    sound: "060-II-I-Am-Solo-Reg-Mix.mp3",
    text: "io sono",
    synonym: "distante",
  },
  {
    soundNum: "61",
    sound: "061-II-I-Am-Bot-Trio-Mix.mp3",
    text: "io sono",
    synonym: "piccola",
  },
  {
    soundNum: "62",
    sound: "062-II-I-Am-Solo-Hi.mp3",
    text: "io sono",
    synonym: "qua",
  },
  {
    soundNum: "63",
    sound: "063-II-I-Am-Solo-Reg.mp3",
    text: "io sono",
    synonym: "lontano",
  },
  {
    soundNum: "64",
    sound: "064-II-See-Them-2-Ways-Mix.mp3",
    text: "vederli",
    synonym: "insieme",
  },
  {
    soundNum: "65",
    sound: "065-II-You-Are-Singsong-Solo.mp3",
    text: "tu sei",
    synonym: "solo",
  },
  {
    soundNum: "66",
    sound: "066-II-You-Are-Solo-Witch.mp3",
    text: "tu sei",
    synonym: "niente",
  },
  {
    soundNum: "67",
    sound: "067-II-Nobody-Sees-Me-Lo-Plaint.mp3",
    text: "nessuno mi vede",
    synonym: "perso",
  },
  {
    soundNum: "68",
    sound: "068-II-Nobody-Sees-Me-Solo-Reg-Plaint.mp3",
    text: "nessuno mi vede",
    synonym: "nascosta",
  },
  {
    soundNum: "69",
    sound: "069-II-Nobody-Sees-Me-Pleased-Solo-Reg.mp3",
    text: "nessuno mi vede",
    synonym: "invisibile",
  },
  {
    soundNum: "70",
    sound: "070-II-Be-Me-Point-At-Self-Lo-Slo-Old.mp3",
    text: "sii me",
    synonym: "essere me",
  },
  {
    soundNum: "71",
    sound: "071-II-Be-Me-Solo-Reg.mp3",
    text: "essere me",
    synonym: "essere loro",
  },
  {
    soundNum: "72",
    sound: "072-II-Be-Me-Multi-Mix.mp3",
    text: "sii me",
    synonym: "libero",
  },
  {
    soundNum: "73",
    sound: "073-II-Be-Me-Point-At-Self-Solo.mp3",
    text: "sii me",
    synonym: "esisto",
  },
  {
    soundNum: "74",
    sound: "074-II-Sometimes-I-Am-mixed-up.mp3",
    text: "a volte io sono",
    synonym: "invisibile",
  },
]

export default it
