const de = [
  {
    soundNum: "1",
    sound: "01_siasingsonggirl.mp3",
    text: "manchmal bin ich",
    synonym: "ungesehen",
  },
  {
    soundNum: "2",
    sound: "02_siastern.mp3",
    text: "manchmal bin ich",
    synonym: "unsichtbar",
  },
  {
    soundNum: "3",
    sound: "03_simamix.mp3",
    text: "manchmal bin ich",
    synonym: "",
  },
  {
    soundNum: "4",
    sound: "04_wearethree.mp3",
    text: "wir sind",
    synonym: "hier",
  },
  {
    soundNum: "5",
    sound: "05_wearesure.mp3",
    text: "wir sind",
    synonym: "stark",
  },
  {
    soundNum: "6",
    sound: "06_wearereadyforus.mp3",
    text: "wir sind",
    synonym: "nicht allein",
  },
  {
    soundNum: "7",
    sound: "07_theyaredefmix.mp3",
    text: "sie sind",
    synonym: "unsichtbar",
  },
  {
    soundNum: "8",
    sound: "08_theyarefirmgirlmix.mp3",
    text: "sie sind",
    synonym: "anwesend",
  },
  {
    soundNum: "9",
    sound: "09_wecandefmix.mp3",
    text: "wir können",
    synonym: "vorgeben",
  },
  {
    soundNum: "10",
    sound: "10_wecanreallymix.mp3",
    text: "wir können",
    synonym: "verschwinden",
  },
  {
    soundNum: "11",
    sound: "11_wecanyourekiddingmix.mp3",
    text: "wir können",
    synonym: "nicht",
  },
  {
    soundNum: "12",
    sound: "12_theycanofcoursemix.mp3",
    text: "sie können",
    synonym: "verschwinden",
  },
  {
    soundNum: "13",
    sound: "13_theycanthemtypes.mp3",
    text: "sie können",
    synonym: "verlieren",
  },
  {
    soundNum: "14",
    sound: "14_wecantnpe.mp3",
    text: "wir können nicht",
    synonym: "weg",
  },
  {
    soundNum: "15",
    sound: "15_youareold.mp3",
    text: "du bist",
    synonym: "distanziert",
  },
  {
    soundNum: "16",
    sound: "16_youaregirl.mp3",
    text: "du bist",
    synonym: "frei",
  },
  {
    soundNum: "17",
    sound: "17_youaresure.mp3",
    text: "du bist",
    synonym: "grossartig",
  },
  {
    soundNum: "18",
    sound: "18_youaredouble.mp3",
    text: "du bist",
    synonym: "anders",
  },
  {
    soundNum: "19",
    sound: "19_beyoudef.mp3",
    text: "sei du selbst",
    synonym: "",
  },
  {
    soundNum: "20",
    sound: "20_beyousingsong.mp3",
    text: "",
    synonym: "unabhängig",
  },
  {
    soundNum: "21",
    sound: "21_bethemyep.mp3",
    text: "sehe sie",
    synonym: "gemeinsam",
  },
  {
    soundNum: "22",
    sound: "22_bethemchantmix.mp3",
    text: "sei sie",
    synonym: "zufrieden",
  },
  {
    soundNum: "23",
    sound: "23_betheminterrogatemix.mp3",
    text: "sie sein",
    synonym: "ungezwungen",
  },
  {
    soundNum: "24",
    sound: "24_inbisiblesingsongmix.mp3",
    text: "unsichtbar",
    synonym: "fern",
  },
  {
    soundNum: "25",
    sound: "25_invisiblesterndefmix.mp3",
    text: "unsichtbar",
    synonym: "verschwunden",
  },
  {
    soundNum: "26",
    sound: "26_invisiblewhispermix.mp3",
    text: "unsichtbar",
    synonym: "weg",
  },
  {
    soundNum: "27",
    sound: "27_invisibleresignmix.mp3",
    text: "unsichtbar",
    synonym: "abwesend",
  },
  {
    soundNum: "28",
    sound: "28_invisiblepitchsyllablemix.mp3",
    text: "unsichtbar",
    synonym: "entfernt",
  },
  {
    soundNum: "29",
    sound: "29_invisvoiceofexpmix.mp3",
    text: "unsichtbar",
    synonym: "weit entfernt",
  },
  {
    soundNum: "30",
    sound: "30_invisladyhoo.mp3",
    text: "unsichtbar",
    synonym: "ich bin",
  },
  {
    soundNum: "31",
    sound: "31_seethemallmix.mp3",
    text: "sieh die",
    synonym: "dort",
  },
  {
    soundNum: "32",
    sound: "32_seethemrightthere.mp3",
    text: "sieh die",
    synonym: "hier",
  },
  {
    soundNum: "33",
    sound: "33_seetheminsistmix.mp3",
    text: "sieh die",
    synonym: "zusammen",
  },
  {
    soundNum: "34",
    sound: "34_seethemsingsong.mp3",
    text: "sieh mich",
    synonym: "sieh die",
  },
  {
    soundNum: "35",
    sound: "35_seethempetulant.mp3",
    text: "sieh mich",
    synonym: "grossartig",
  },
  {
    soundNum: "36",
    sound: "36_seethemfadeout.mp3",
    text: "sei mich",
    synonym: "sichtbar",
  },
  {
    soundNum: "37",
    sound: "37_siaoldsoulmix.mp3",
    text: "manchmal bin ich",
    synonym: "müde",
  },
  {
    soundNum: "38",
    sound: "38_siasternerstuff.mp3",
    text: "manchmal bin ich",
    synonym: "stark",
  },
  {
    soundNum: "39",
    sound: "39_siathree.mp3",
    text: "manchmal bin ich",
    synonym: "schnell",
  },
  {
    soundNum: "40",
    sound: "40_siamixedup.mp3",
    text: "manchmal bin ich",
    synonym: "nachdenklich",
  },
  {
    soundNum: "41",
    sound: "41_seeyoubememix.mp3",
    text: "sehe dich",
    synonym: "sie können nicht",
  },
  {
    soundNum: "42",
    sound: "42_seeyougirlmix.mp3",
    text: "sehe dich",
    synonym: "lachen",
  },
  {
    soundNum: "43",
    sound: "43_theyaresure.mp3",
    text: "sie sind",
    synonym: "ängstlich",
  },
  {
    soundNum: "44",
    sound: "44_theyarewhatever.mp3",
    text: "sie sind",
    synonym: "traurig",
  },
  {
    soundNum: "45",
    sound: "45_youcaninsist.mp3",
    text: "du kannst nicht",
    synonym: "alleine",
  },
  {
    soundNum: "46",
    sound: "46_youcanlodef.mp3",
    text: "du kannst nicht",
    synonym: "wir können",
  },
  {
    soundNum: "47",
    sound: "47_theyreallycanmix.mp3",
    text: "sie können nicht",
    synonym: "sie sein",
  },
  {
    soundNum: "48",
    sound: "48_thecantforsure.mp3",
    text: "die können nicht",
    synonym: "ich schon",
  },
  {
    soundNum: "49",
    sound: "49_iamplain.mp3",
    text: "ich bin",
    synonym: "du bist",
  },
  {
    soundNum: "50",
    sound: "50_iamcho.mp3",
    text: "ich bin",
    synonym: "verwundert",
  },
  {
    soundNum: "51",
    sound: "51_iamvrmix.mp3",
    text: "ich bin",
    synonym: "zuversichtlich",
  },
  {
    soundNum: "52",
    sound: "52_youcantseemedefmix.mp3",
    text: "du kannst",
    synonym: "mich nicht sehen",
  },
  {
    soundNum: "53",
    sound: "53_youcantseemecoymix.mp3",
    text: "du kannst mich nicht sehen",
    synonym: "",
  },
  {
    soundNum: "54",
    sound: "54_youcantseemeghostmix.mp3",
    text: "du kannst mich nicht sehen",
    synonym: "verloren",
  },
  {
    soundNum: "55",
    sound: "55_youcantseememix.mp3",
    text: "",
    synonym: "verwirrt",
  },
  {
    soundNum: "56",
    sound: "56_iamsingsong.mp3",
    text: "ich bin",
    synonym: "froh",
  },
  {
    soundNum: "57",
    sound: "57_iamplainmix.mp3",
    text: "ich bin",
    synonym: "allein",
  },
  {
    soundNum: "58",
    sound: "58_iamsnippymix.mp3",
    text: "ich bin",
    synonym: "anwesend",
  },
  {
    soundNum: "59",
    sound: "59_iamsomehow.mp3",
    text: "ich bin",
    synonym: "erkennbar",
  },
  {
    soundNum: "60",
    sound: "60_iammix.mp3",
    text: "ich bin",
    synonym: "anders",
  },
  {
    soundNum: "61",
    sound: "61_iamwhatmix.mp3",
    text: "ich bin",
    synonym: "erstaunt",
  },
  {
    soundNum: "62",
    sound: "62_seethemcronemix.mp3",
    text: "seh sie",
    synonym: "träumend",
  },
  {
    soundNum: "63",
    sound: "63_seethemurgentmix.mp3",
    text: "seh sie",
    synonym: "trauernd",
  },
  {
    soundNum: "64",
    sound: "64_youarechorusmix.mp3",
    text: "du bist",
    synonym: "fantastisch",
  },
  {
    soundNum: "65",
    sound: "65_youarejudgeygirl.mp3",
    text: "du bist",
    synonym: "unsichtbar",
  },
  {
    soundNum: "66",
    sound: "66_invisbelltoll.mp3",
    text: "unsichtbar",
    synonym: "unentdeckt",
  },
  {
    soundNum: "67",
    sound: "67_nbdystern.mp3",
    text: "niemand sieht mich",
    synonym: "verschleiert",
  },
  {
    soundNum: "68",
    sound: "68_nbody.mp3",
    text: "niemand sieht mich",
    synonym: "verborgen",
  },
  {
    soundNum: "69",
    sound: "69_nobodybackforthemix.mp3",
    text: "niemand sieht mich",
    synonym: "verkleidet",
  },
  {
    soundNum: "70",
    sound: "70_nbdyseememix.mp3",
    text: "niemand sieht mich",
    synonym: "ausgeflogen",
  },
  {
    soundNum: "71",
    sound: "71_bememix.mp3",
    text: "sei mich",
    synonym: "sei du",
  },
  {
    soundNum: "72",
    sound: "72_siachorus.mp3",
    text: "manchmal bin ich",
    synonym: "vertieft",
  },
  {
    soundNum: "73",
    sound: "73_bemeslowmix.mp3",
    text: "sei mich",
    synonym: "sichtbar,",
  },
  {
    soundNum: "74",
    sound: "74_bemechorusmix.mp3",
    text: "sei mich",
    synonym: "wir sind",
  },
]

export default de
