const ur = [
  {
    soundNum: "1",
    sound: "01_urdu_siadef.mp3",
    text: "کبھی کبھی میں",
    synonym: "چھپے ہوۓ",
  },
  {
    soundNum: "2",
    sound: "02_urdu_sianorm.mp3",
    text: "کبھی کبھی میں",
    synonym: "گمشدہ",
  },
  {
    soundNum: "3",
    sound: "03_urdu_siadeffold.mp3",
    text: "کبھی کبھی میں",
    synonym: "پوشیدہ",
  },
  {
    soundNum: "4",
    sound: "04_urdu_siaque.mp3",
    text: "کبھی کبھی میں",
    synonym: "اکیلی",
  },
  {
    soundNum: "5",
    sound: "05_urdu_siafun.mp3",
    text: "کبھی کبھی میں",
    synonym: "اداس",
  },
  {
    soundNum: "6",
    sound: "06_urdu_wearemix.mp3",
    text: "ہم",
    synonym: "ہم نہیں کر سکتے",
  },
  {
    soundNum: "7",
    sound: "07_urdu_wearequery.mp3",
    text: "ہم",
    synonym: "چلے گۓ",
  },
  {
    soundNum: "8",
    sound: "08_urdu_wearejoke.mp3",
    text: "ہم",
    synonym: "اکیلے نہیں",
  },
  {
    soundNum: "9",
    sound: "09_urdu_wearenorm.mp3",
    text: "ہم",
    synonym: "مختلف",
  },
  {
    soundNum: "10",
    sound: "10_urdu_theyaremuse.mp3",
    text: "وہ",
    synonym: "غیر حاضر",
  },
  {
    soundNum: "11",
    sound: "11_urdu_theyareeexp.mp3",
    text: "وہ",
    synonym: "غائب",
  },
  {
    soundNum: "12",
    sound: "12_urdu_theyarewondermix.mp3",
    text: "وہ",
    synonym: "مطمۂن",
  },
  {
    soundNum: "13",
    sound: "13_urdu_wecanchorus.mp3",
    text: "ہم کر سکتے ہیں",
    synonym: "سب کچھ",
  },
  {
    soundNum: "14",
    sound: "14_urdu_wecandef.mp3",
    text: "ہم کر سکتے ہیں",
    synonym: "مضبوط",
  },
  {
    soundNum: "15",
    sound: "15_urdu_wecanquestmix.mp3",
    text: "ہم کر سکتے ہیں",
    synonym: "دکھاوے",
  },
  {
    soundNum: "16",
    sound: "16_urdu_theycanmix.mp3",
    text: "وہ کر سکتے ہیں",
    synonym: "اکیلے نہیں",
  },
  {
    soundNum: "17",
    sound: "17_urdu_theycanmix.mp3",
    text: "وہ کر سکتے ہیں",
    synonym: "کچھ نہیں",
  },
  {
    soundNum: "18",
    sound: "18_urdu_theycanmix.mp3",
    text: "وہ کر سکتے ہیں",
    synonym: "لاپتہ",
  },
  {
    soundNum: "19",
    sound: "19_urdu_wecantrebelmix.mp3",
    text: "ہم نہیں کر سکتے",
    synonym: "نا ممکن",
  },
  {
    soundNum: "20",
    sound: "20_urdu_youaremix.mp3",
    text: "ہم",
    synonym: "مضبوط",
  },
  {
    soundNum: "21",
    sound: "21_urdu_youaremixI.mp3",
    text: "ہم",
    synonym: "وہ ہیں",
  },
  {
    soundNum: "22",
    sound: "22_urdu_youaremix.mp3",
    text: "ہم",
    synonym: "مطمۂن",
  },
  {
    soundNum: "23",
    sound: "23_urdu_beyoumix.mp3",
    text: "تم ہو",
    synonym: "تم ہو/آپ ہیں/ آپ ہی  ہیں",
  },
  {
    soundNum: "24",
    sound: "24_urdu_beyoumix.mp3",
    text: "آپ ہی  ہیں",
    synonym: "ایک ساتھ",
  },
  {
    soundNum: "25",
    sound: "25_urdu_bethemmix.mp3",
    text: "وہ ہیں",
    synonym: "مختلف",
  },
  {
    soundNum: "26",
    sound: "26_urdu_bethemmix.mp3",
    text: "وہ ہیں",
    synonym: "غيبی",
  },
  {
    soundNum: "27",
    sound: "27_urdu_bethemdefmix.mp3",
    text: "وہ ہیں",
    synonym: "غیر حاضر",
  },
  {
    soundNum: "28",
    sound: "28_urdu_invisiblesinmix.mp3",
    text: "پوشیدہ",
    synonym: "لاپتہ",
  },
  {
    soundNum: "29",
    sound: "29_urdu_invissombremix.mp3",
    text: "غائب ہونا",
    synonym: "چلے گۓ",
  },
  {
    soundNum: "30",
    sound: "30_urdu_invisecho.mp3",
    text: "پوشیدہ",
    synonym: "اکیلے",
  },
  {
    soundNum: "31",
    sound: "31_urdu_invisghost.mp3",
    text: "پوشیدہ",
    synonym: "یہاں",
  },
  {
    soundNum: "32",
    sound: "32_urdu_invisinsistentghost.mp3",
    text: "پوشیدہ",
    synonym: "سب کچھ",
  },
  {
    soundNum: "33",
    sound: "33_urdu_invispluralmix.mp3",
    text: "چھپی ہوئی",
    synonym: "",
  },
  {
    soundNum: "34",
    sound: "34_urdu_ivisfemalemix.mp3",
    text: "چھپی ہوئی",
    synonym: "دکھاوا",
  },
  {
    soundNum: "35",
    sound: "35_urdu_invismutlimixI.mp3",
    text: "چھپی ہوئی",
    synonym: "اکیلی",
  },
  {
    soundNum: "36",
    sound: "36_urdu_invismale.mp3",
    text: "چھپا ہوا",
    synonym: "دور",
  },
  {
    soundNum: "37",
    sound: "37_urdu_invischorus.mp3",
    text: "چھپ چھپ ",
    synonym: "مختلف",
  },
  {
    soundNum: "38",
    sound: "38_urdu_youcantgirlboywhis.mp3",
    text: "تم نہیں کر سکتے",
    synonym: "نا ممکن",
  },
  {
    soundNum: "39",
    sound: "39_urdu_hidden.mp3",
    text: "چھپ چھپ",
    synonym: "",
  },
  {
    soundNum: "40",
    sound: "40_urdu_seethemmix.mp3",
    text: "انہیں دیکھو",
    synonym: "غم",
  },
  {
    soundNum: "41",
    sound: "41_urdu_seethemfarmixI.mp3",
    text: "انہیں دیکھو",
    synonym: "ڈرنا",
  },
  {
    soundNum: "42",
    sound: "42_urdu_seethemechomix.mp3",
    text: "انہیں دیکھو",
    synonym: "کچھ نہ ہونا",
  },
  {
    soundNum: "43",
    sound: "43_urdu_seememix.mp3",
    text: "مجھے دیکھو",
    synonym: "میرے جیسا بنو",
  },
  {
    soundNum: "44",
    sound: "44_urdu_seeme_permix.mp3",
    text: "مجھے دیکھو",
    synonym: "غیر حاضر",
  },
  {
    soundNum: "45",
    sound: "45_urdu_seemepolimix.mp3",
    text: "مجھے دیکھو",
    synonym: "ادھر نہیں",
  },
  {
    soundNum: "46",
    sound: "46_urdu_siasuremix.mp3",
    text: "کبھی کبھی میں",
    synonym: "دور",
  },
  {
    soundNum: "47",
    sound: "47_urdu_siaallmix.mp3",
    text: "کبھی کبھی میں",
    synonym: "غیر موجود",
  },
  {
    soundNum: "48",
    sound: "48_urdu_siaconfess.mp3",
    text: "کبھی کبھی میں",
    synonym: "غم",
  },
  {
    soundNum: "49",
    sound: "49_urdu_siasocietymix .mp3",
    text: "کبھی کبھی میں",
    synonym: "مضبوط",
  },
  {
    soundNum: "50",
    sound: "50_urdu_seeyouIsistermix.mp3",
    text: "دیکھنا",
    synonym: "سب کچھ",
  },
  {
    soundNum: "51",
    sound: "51_urdu_seeyouchorus.mp3",
    text: "دیکھنا",
    synonym: "ایک ساتھ",
  },
  {
    soundNum: "52",
    sound: "52_urdu_seeyou_sistermixpos.mp3",
    text: "وہ ہیں",
    synonym: "فارغ",
  },
  {
    soundNum: "53",
    sound: "53_urdu_theyarepraisemix.mp3",
    text: "وہ ہیں",
    synonym: "غائب",
  },
  {
    soundNum: "54",
    sound: "54_theyareprobmix.mp3",
    text: "وہ ہیں",
    synonym: "نظر آنے والے",
  },
  {
    soundNum: "55",
    sound: "55_urdu_seethemreallymix.mp3",
    text: "انہیں دیکھو",
    synonym: "موجود",
  },
  {
    soundNum: "56",
    sound: "56_urdu_seethemghostmix.mp3",
    text: "انہیں دیکھو",
    synonym: "گمشدہ",
  },
  {
    soundNum: "57",
    sound: "57_urdu_seethemangryghostmixI.mp3",
    text: "انہیں دیکھو",
    synonym: "اکیلی",
  },
  {
    soundNum: "58",
    sound: "58_urdu_youcanemphmix.mp3",
    text: "تم نہیں کر سکتے",
    synonym: "نا ممکن",
  },
  {
    soundNum: "59",
    sound: "59_urdu_youcantempmix.mp3",
    text: "تم نہیں کرسکتی",
    synonym: "دکھاوا",
  },
  {
    soundNum: "60",
    sound: "60_urdu_youcanallgenderwhisper.mp3",
    text: "تم نہیں کر سکتے",
    synonym: "غم",
  },
  {
    soundNum: "61",
    sound: "61_urdu_theycantmix.mp3",
    text: "وہ نہیں کر سکتے",
    synonym: "اکیلے نہیں",
  },
  {
    soundNum: "62",
    sound: "62_urdu_theycantwontmix.mp3",
    text: "وہ نہیں کر سکتے",
    synonym: "کچھ نہ ہونا",
  },
  {
    soundNum: "63",
    sound: "63_urdu_iamsimpmixI.mp3",
    text: "میں ہوں",
    synonym: "دور",
  },
  {
    soundNum: "64",
    sound: "64_urdu_iamemphmix.mp3",
    text: "میں ہوں",
    synonym: "اکیلے",
  },
  {
    soundNum: "65",
    sound: "65_urdu_iamsecret.mp3",
    text: "میں ہوں",
    synonym: "میرے جیسا بنو",
  },
  {
    soundNum: "66",
    sound: "66_urdu_seethemmix.mp3",
    text: "انہیں دیکھو",
    synonym: "موجود",
  },
  {
    soundNum: "67",
    sound: "67_urdu_seethemaccumix.mp3",
    text: "انہیں دیکھو",
    synonym: "مجھے دیکھو",
  },
  {
    soundNum: "68",
    sound: "68_urdu_youarecrowdmix.mp3",
    text: "آپ ہیں",
    synonym: "غیر حاض",
  },
  {
    soundNum: "69",
    sound: "69_urdu_youareonlymix.mp3",
    text: "تم ہو",
    synonym: "لاپتہ",
  },
  {
    soundNum: "70",
    sound: "70_urdu_youarepersmix.mp3",
    text: "تم ہو",
    synonym: "دور",
  },
  {
    soundNum: "71",
    sound: "71_urdu_nobodyseesmemix.mp3",
    text: "مجھے کوئی نہیں دیکھتا",
    synonym: "دکھاوے",
  },
  {
    soundNum: "72",
    sound: "72_urdu_nobodyseesmeregretmix.mp3",
    text: "مجھے کوئی نہیں دیکھتا",
    synonym: "",
  },
  {
    soundNum: "73",
    sound: "73_urdu_bememix.mp3",
    text: "میرے جیسا بنو",
    synonym: "مضبوط",
  },
  {
    soundNum: "74",
    sound: "74_urdu_bemeeasymix.mp3",
    text: "میرے جیسا بنو",
    synonym: "مطمۂن",
  },
]

export default ur
