const fr = [
  {
    soundNum: "1",
    sound: "01sometimesdefhi.mp3",
    text: "parfois je suis",
    synonym: "caché(e)",
  },
  {
    soundNum: "2",
    sound: "02sometimesdefmid.mp3",
    text: "parfois je suis",
    synonym: "perdu(e)",
  },
  {
    soundNum: "3",
    sound: "03sometimesdefrepmulti.mp3",
    text: "des fois je suis",
    synonym: "invisible",
  },
  {
    soundNum: "4",
    sound: "04sometimesiamqmulti.mp3",
    text: "parfois je suis/des fois je suis",
    synonym: "absent(e)",
  },
  {
    soundNum: "5",
    sound: "05wearessmix.mp3",
    text: "nous sommes ",
    synonym: "différents",
  },
  {
    soundNum: "6",
    sound: "06theyareg1.mp3",
    text: "ils sont",
    synonym: "éloignés",
  },
  {
    soundNum: "7",
    sound: "07theyareg2.mp3",
    text: "elles sont",
    synonym: "parties",
  },
  {
    soundNum: "8",
    sound: "08theyareg3.mp3",
    text: "iels sont",
    synonym: "rien",
  },
  {
    soundNum: "9",
    sound: "09theyarethreess.mp3",
    text: "ieles sont",
    synonym: "tristes",
  },
  {
    soundNum: "10",
    sound: "10wecandefmid.mp3",
    text: "nous pouvons",
    synonym: "disparaître",
  },
  {
    soundNum: "11",
    sound: "11wecandefmix.mp3",
    text: "nous pouvons",
    synonym: "être seuls",
  },
  {
    soundNum: "12",
    sound: "12wecanqsoftblur.mp3",
    text: "nous pouvons",
    synonym: "faire semblant",
  },
  {
    soundNum: "13",
    sound: "13theycanqx3mix.mp3",
    text: "ils peuvent",
    synonym: "être contents",
  },
  {
    soundNum: "14",
    sound: "14theycansuredeep.mp3",
    text: "ils peuvent",
    synonym: "être libres",
  },
  {
    soundNum: "15",
    sound: "15theycansureshecan.mp3",
    text: "elles peuvent",
    synonym: "",
  },
  {
    soundNum: "16",
    sound: "16theycan4suregirls.mp3",
    text: "iels peuvent",
    synonym: "se perdre",
  },
  {
    soundNum: "17",
    sound: "17wecantsadmix.mp3",
    text: "nous ne pouvons pas ",
    synonym: "être ensemble",
  },
  {
    soundNum: "18",
    sound: "18youareaccuse.mp3",
    text: "tu es",
    synonym: "",
  },
  {
    soundNum: "19",
    sound: "19youaresingsongsingle.mp3",
    text: "tu es ",
    synonym: "loin",
  },
  {
    soundNum: "20",
    sound: "20youaresingsonglo.mp3",
    text: "tu es",
    synonym: "petit(e)",
  },
  {
    soundNum: "21",
    sound: "21youaresingsonghi.mp3",
    text: "tu es",
    synonym: "rien",
  },
  {
    soundNum: "22",
    sound: "22beyousingsongplaygroundmix.mp3",
    text: "sois toi",
    synonym: "",
  },
  {
    soundNum: "23",
    sound: "23beyouexapergirl.mp3",
    text: "sois toi",
    synonym: "sois moi",
  },
  {
    soundNum: "24",
    sound: "24bethemsingout3.mp3",
    text: "soyez eux",
    synonym: "ensemble",
  },
  {
    soundNum: "25",
    sound: "25beyouexapercrone.mp3",
    text: "sois toi",
    synonym: "tout seul",
  },
  {
    soundNum: "26",
    sound: "26bethemsingouthighecho.mp3",
    text: "soyez eux",
    synonym: "",
  },
  {
    soundNum: "27",
    sound: "27bethemyoutryladies.mp3",
    text: "soyez eux",
    synonym: "effrayés",
  },
  {
    soundNum: "28",
    sound: "28invissoftreg.mp3",
    text: "invisible",
    synonym: "absent",
  },
  {
    soundNum: "29",
    sound: "29invissoftgirls.mp3",
    text: "invisible",
    synonym: "cachée",
  },
  {
    soundNum: "30",
    sound: "30invisfastangrywitch.mp3",
    text: "invisible",
    synonym: "rien",
  },
  {
    soundNum: "31",
    sound: "31invissyllablemix.mp3",
    text: "invisible",
    synonym: "",
  },
  {
    soundNum: "32",
    sound: "32invissyllablesadgran.mp3",
    text: "invisible",
    synonym: "invisible",
  },
  {
    soundNum: "33",
    sound: "33invissilentghostz.mp3",
    text: "invisible",
    synonym: "",
  },
  {
    soundNum: "34",
    sound: "34invissilentghostgirlz.mp3",
    text: "invisible",
    synonym: "disparu",
  },
  {
    soundNum: "35",
    sound: "35invissilentghostgasp.mp3",
    text: "invisible",
    synonym: "",
  },
  {
    soundNum: "36",
    sound: "36invisloud.mp3",
    text: "invisible",
    synonym: "je suis",
  },
  {
    soundNum: "37",
    sound: "37invisloudbratz.mp3",
    text: "invisible",
    synonym: "petite",
  },
  {
    soundNum: "38",
    sound: "38invissadddgirl.mp3",
    text: "invisible",
    synonym: "inexistante",
  },
  {
    soundNum: "39",
    sound: "39invisplayfultauntmix.mp3",
    text: "invisible",
    synonym: "",
  },
  {
    soundNum: "40",
    sound: "40seethemssongechomix.mp3",
    text: "regardez-les",
    synonym: "aller",
  },
  {
    soundNum: "41",
    sound: "41seethemspeechdefsong.mp3",
    text: "",
    synonym: "ensemble",
  },
  {
    soundNum: "42",
    sound: "42seemelook2wice.mp3",
    text: "regardez moi ",
    synonym: "",
  },
  {
    soundNum: "43",
    sound: "43seemehidenseek.mp3",
    text: "regardez mois",
    synonym: "forte",
  },
  {
    soundNum: "44",
    sound: "44sometimeiamquery3.mp3",
    text: "parfois je suis",
    synonym: "perdu",
  },
  {
    soundNum: "45",
    sound: "45sometimesdefrepmix.mp3",
    text: "parfois je suis",
    synonym: "loin",
  },
  {
    soundNum: "46",
    sound: "46sometimessofty.mp3",
    text: "parfois je suis",
    synonym: "",
  },
  {
    soundNum: "47",
    sound: "47sometimessoftymanymix.mp3",
    text: "parfois je suis",
    synonym: "folle",
  },
  {
    soundNum: "48",
    sound: "48seeyoulookatyouparentmix.mp3",
    text: "regarde toi",
    synonym: "seul",
  },
  {
    soundNum: "49",
    sound: "49seeyousingsongmix.mp3",
    text: "je te vois",
    synonym: "",
  },
  {
    soundNum: "50",
    sound: "50seeyousingsonglater.mp3",
    text: "je te vois",
    synonym: "parti",
  },
  {
    soundNum: "51",
    sound: "51theyaredefhe.mp3",
    text: "ils sont",
    synonym: "libres",
  },
  {
    soundNum: "52",
    sound: "52theyaredefshe.mp3",
    text: "elles sont",
    synonym: "puissantes",
  },
  {
    soundNum: "53",
    sound: "53theyaredefthey.mp3",
    text: "iels sont",
    synonym: "fâchés",
  },
  {
    soundNum: "54",
    sound: "54theyareall3query.mp3",
    text: "ils sont",
    synonym: "différent(e)s",
  },
  {
    soundNum: "55",
    sound: "55theyareallmixedup.mp3",
    text: "iels sont",
    synonym: "ici",
  },
  {
    soundNum: "56",
    sound: "56seetheminsistdbl.mp3",
    text: "regardez-les",
    synonym: "faire semblant",
  },
  {
    soundNum: "57",
    sound: "57seethemallmix.mp3",
    text: "regardez-les",
    synonym: "content(e)s",
  },
  {
    soundNum: "58",
    sound: "58seethemsoffffftmix.mp3",
    text: "regardez",
    synonym: "",
  },
  {
    soundNum: "59",
    sound: "59seethemmysticalcreaturesmix.mp3",
    text: "regardez-les",
    synonym: "unique",
  },
  {
    soundNum: "60",
    sound: "60youcantsadmix.mp3",
    text: "tu ne peux pas",
    synonym: "partir",
  },
  {
    soundNum: "61",
    sound: "61youcantadmonishmix.mp3",
    text: "vous ne pouvez pas",
    synonym: "m'aider",
  },
  {
    soundNum: "62",
    sound: "62theycantsaddisbeliefx3.mp3",
    text: "elles ne peuvent pas",
    synonym: "s'arrêter",
  },
  {
    soundNum: "63",
    sound: "63theycantmadx3.mp3",
    text: "ils ne peuvent pas",
    synonym: "faire ça",
  },
  {
    soundNum: "64",
    sound: "64iamsuresoftmix.mp3",
    text: "je suis",
    synonym: "seul",
  },
  {
    soundNum: "65",
    sound: "65iamdefwisemix.mp3",
    text: "je suis",
    synonym: "sûr",
  },
  {
    soundNum: "66",
    sound: "66youcantseemesadmix .mp3",
    text: "tu ne peux pas",
    synonym: "me voir",
  },
  {
    soundNum: "67",
    sound: "67youcantseemexasperatmix.mp3",
    text: "tu ne peux pas me voir",
    synonym: "triste",
  },
  {
    soundNum: "68",
    sound: "68iamghostmix.mp3",
    text: "je suis",
    synonym: "un fantôme",
  },
  {
    soundNum: "69",
    sound: "69youaredying.mp3",
    text: "tu es",
    synonym: "absent",
  },
  {
    soundNum: "70",
    sound: "70youaretheteamdefmix.mp3",
    text: "vous êtes",
    synonym: "chiant(e)s",
  },
  {
    soundNum: "71",
    sound: "71nobodyseesmeconfessmix.mp3",
    text: "",
    synonym: "",
  },
  {
    soundNum: "72",
    sound: "72nobdyseesmeangrmix.mp3",
    text: "personne ne",
    synonym: "me voit",
  },
  {
    soundNum: "73",
    sound: "73bemeyoutrytight.mp3",
    text: "soit moi",
    synonym: "essayer",
  },
  {
    soundNum: "74",
    sound: "74bemesofttoselfmix.mp3",
    text: "soit moi ",
    synonym: "",
  },
]

export default fr
