const ko = [
  {
    soundNum: "1",
    sound: "01KSOMTIMESDEF3mix.mp3",
    text: "이따금 나는",
    synonym: "보이지 않는다",
  },
  {
    soundNum: "2",
    sound: "02KSOMETIMESQHI.mp3",
    text: "가끔 나는",
    synonym: "아무것도 아니다",
  },
  {
    soundNum: "3",
    sound: "03KSOMETIMESQLO.mp3",
    text: "가끔 나는",
    synonym: "전부이다",
  },
  {
    soundNum: "4",
    sound: "04KWEARESSLILT.mp3",
    text: "우리는",
    synonym: "하는 척한다",
  },
  {
    soundNum: "5",
    sound: "05KWEARESSLAMENT.mp3",
    text: "우리는",
    synonym: "헤멘다",
  },
  {
    soundNum: "6",
    sound: "06KTHEYARESSMISS.mp3",
    text: "그들은",
    synonym: "작다",
  },
  {
    soundNum: "7",
    sound: "07KTHEYARESSMAAM.mp3",
    text: "그들은",
    synonym: "헤멘다",
  },
  {
    soundNum: "8",
    sound: "08KTHEYAREQ3.mp3",
    text: "그들이",
    synonym: "나를 본다",
  },
  {
    soundNum: "9",
    sound: "09KWECANDEFWISE.mp3",
    text: "우리는 할 수 있다",
    synonym: "",
  },
  {
    soundNum: "10",
    sound: "10KWECANQ.mp3",
    text: "우리는 할 수 있다",
    synonym: "너는 할 수 없다",
  },
  {
    soundNum: "11",
    sound: "11KTHEYCANQWISE.mp3",
    text: "우리는 할 수 있다",
    synonym: "네가 되는 것",
  },
  {
    soundNum: "12",
    sound: "12KTHEYCANQHI.mp3",
    text: "우리는 할 수 있다",
    synonym: "함께이다",
  },
  {
    soundNum: "13",
    sound: "13KTHEYCANSUREMID.mp3",
    text: "우리는 할 수 있다",
    synonym: "아무것도 갖고있지 않다",
  },
  {
    soundNum: "14",
    sound: "14KWECANTSADAGING.mp3",
    text: "우리는 할 수 있다",
    synonym: "슬프다",
  },
  {
    soundNum: "15",
    sound: "15KWECANTSADYOUTH.mp3",
    text: "우리는 할 수 없다",
    synonym: "멀리 있다",
  },
  {
    soundNum: "16",
    sound: "16KYOUAREPRAISEDOTING.mp3",
    text: "당신은",
    synonym: "실종된다",
  },
  {
    soundNum: "17",
    sound: "17KYOUAREBADGRAM.mp3",
    text: "당신은",
    synonym: "당신이다",
  },
  {
    soundNum: "18",
    sound: "18KYOUARESSECHO.mp3",
    text: "당신은",
    synonym: "보인다",
  },
  {
    soundNum: "19",
    sound: "19KBEYOUSS.mp3",
    text: "네가 되는 것",
    synonym: "그들이 되는 것",
  },
  {
    soundNum: "20",
    sound: "20KBEYOUPLEASEKID.mp3",
    text: "네가 되는 것",
    synonym: "",
  },
  {
    soundNum: "21",
    sound: "21KBEYOUSTERNELDER.mp3",
    text: "네가 되는 것",
    synonym: "내가 되서 나를 본다",
  },
  {
    soundNum: "22",
    sound: "22KBETHEMSS.mp3",
    text: "그들이 되는 것",
    synonym: "우리는 자유롭다",
  },
  {
    soundNum: "23",
    sound: "23KBETHEMYOUTRYMIX.mp3",
    text: "그들이 되는 것",
    synonym: "그들은 강하다",
  },
  {
    soundNum: "24",
    sound: "24KINVISSOFTMIX.mp3",
    text: "보이지 않는",
    synonym: "아득하다 나는",
  },
  {
    soundNum: "25",
    sound: "25KINVISURGENTMIX.mp3",
    text: "보이지 않는",
    synonym: "존재하지 않는다",
  },
  {
    soundNum: "26",
    sound: "26KINVISSYLL.mp3",
    text: "보이지 않는",
    synonym: "너를 본다",
  },
  {
    soundNum: "27",
    sound: "27KINVISWHISPERMIX.mp3",
    text: "보이지 않는",
    synonym: "숨겨져 있다",
  },
  {
    soundNum: "28",
    sound: "28KINVISLOUDADMONISH.mp3",
    text: "보이지 않는",
    synonym: "여기에 없다",
  },
  {
    soundNum: "29",
    sound: "29KINVISSADSONG.mp3",
    text: "보이지 않는",
    synonym: "내가 되서 나를 본다",
  },
  {
    soundNum: "30",
    sound: "30KINVISPLAYCURSE.mp3",
    text: "보이지 않는",
    synonym: "사라진다",
  },
  {
    soundNum: "31",
    sound: "31KINVISPLAYTAUNTSONG.mp3",
    text: "보이지 않는",
    synonym: "그들을 본다",
  },
  {
    soundNum: "32",
    sound: "32KSEETHEMSSSPOKEN.mp3",
    text: "그들을 본다",
    synonym: "그들은 멀리 있다",
  },
  {
    soundNum: "33",
    sound: "33KSEETHEMSSSPOKENOLDSOULMIX.mp3",
    text: "그들을 본다",
    synonym: "그들은 존재한다",
  },
  {
    soundNum: "34",
    sound: "34KSEETHEMLOOKSPOKENSTERN.mp3",
    text: "그들을 본다",
    synonym: "홀로 있다, 나는",
  },
  {
    soundNum: "35",
    sound: "35KSEETHEMLOOKSPOKENTOOMANYMIX.mp3",
    text: "그들을 본다",
    synonym: "",
  },
  {
    soundNum: "36",
    sound: "36KSEEMELOOKTWEENMIX.mp3",
    text: "나를 본다",
    synonym: "나는 혼자가 아니다",
  },
  {
    soundNum: "37",
    sound: "37KSEEMELOOKGRANNYMIX.mp3",
    text: "그들을 본다",
    synonym: "멀어져 있다",
  },
  {
    soundNum: "38",
    sound: "38KSEEMESS.mp3",
    text: "나를 본다",
    synonym: "당신은 다르다",
  },
  {
    soundNum: "39",
    sound: "39KSEEMESSWITCHMIX.mp3",
    text: "나를 본다",
    synonym: "그들은 충만하다",
  },
  {
    soundNum: "40",
    sound: "40KSOMETIMESQCORRECTTEACH.mp3",
    text: "이따금 나는",
    synonym: "너와 함께이다",
  },
  {
    soundNum: "41",
    sound: "41KSOMETIMESQCORRECTSTUDENTS.mp3",
    text: "이따금 나는",
    synonym: "보이지 않는 당신이다",
  },
  {
    soundNum: "42",
    sound: "42SOMETIMES4SUREMIX.mp3",
    text: "이따금 나는",
    synonym: "보이지 않는 내가 된다",
  },
  {
    soundNum: "43",
    sound: "43SOMETIMESSUREGIRL.mp3",
    text: "이따금 나는",
    synonym: "다르다",
  },
  {
    soundNum: "44",
    sound: "44KSEEYOUSTERN.mp3",
    text: "너를 본다",
    synonym: "너는 할 수 없다",
  },
  {
    soundNum: "45",
    sound: "45KSEEYOUSS.mp3",
    text: "너를 본다",
    synonym: "",
  },
  {
    soundNum: "46",
    sound: "46KSEEYOUSSSURROUND.mp3",
    text: "너를 본다",
    synonym: "",
  },
  {
    soundNum: "47",
    sound: "47KTHEYAREDEFDEF.mp3",
    text: "그들은",
    synonym: "실종된다",
  },
  {
    soundNum: "48",
    sound: "48KTHEYAREDEFMISSMIX.mp3",
    text: "그들은",
    synonym: "여기에 없다",
  },
  {
    soundNum: "49",
    sound: "49KTHEYAREQSHOCKMIX.mp3",
    text: "그들은",
    synonym: "보인다",
  },
  {
    soundNum: "50",
    sound: "50KSEETHEMINSISTSENIOR.mp3",
    text: "그들을 본다",
    synonym: "나는 충만하다",
  },
  {
    soundNum: "51",
    sound: "51KSEETHEMSOFTECHO.mp3",
    text: "그들을 본다",
    synonym: "우리는 여기 있다",
  },
  {
    soundNum: "52",
    sound: "52KSEETHEMSOFT.mp3",
    text: "그들을 본다",
    synonym: "그들은 비통하다",
  },
  {
    soundNum: "53",
    sound: "53KTHEYCANTSADLY2.mp3",
    text: "",
    synonym: "우리는 할 수 있다",
  },
  {
    soundNum: "54",
    sound: "54KTHEYCANTSADGIRLS.mp3",
    text: "그들은 할 수 없다",
    synonym: "헤멘다, 나는",
  },
  {
    soundNum: "55",
    sound: "55KTHEYCANTMADMATRIARCHZ.mp3",
    text: "그들은 할 수 없다",
    synonym: "그들은 아무것도 아니다",
  },
  {
    soundNum: "56",
    sound: "56KAMDEFBOB.mp3",
    text: "나는",
    synonym: "전부이다",
  },
  {
    soundNum: "57",
    sound: "57KIAMDEFCRONE.mp3",
    text: "나는",
    synonym: "자유롭다",
  },
  {
    soundNum: "58",
    sound: "58KIAMSOFTSURE.mp3",
    text: "나는",
    synonym: "나를 본다",
  },
  {
    soundNum: "59",
    sound: "59KIAMSOFTSUREDREAM.mp3",
    text: "나는",
    synonym: "본다, 너를",
  },
  {
    soundNum: "60",
    sound: "60KYOUCANTSEEMESADDDGIRL.mp3",
    text: "너는 나를 볼 수 없다",
    synonym: "",
  },
  {
    soundNum: "61",
    sound: "61YOUCANTSEEMESADDDAGE.mp3",
    text: "너는 나를 볼 수 없다",
    synonym: "너는 가버린다",
  },
  {
    soundNum: "62",
    sound: "62THYECANTMADURGENTMIX.mp3",
    text: "너는 나를 볼 수 없다",
    synonym: "나는 작다",
  },
  {
    soundNum: "63",
    sound: "63IAMGHOSTGLITCH.mp3",
    text: "나는",
    synonym: "떠다닌다",
  },
  {
    soundNum: "64",
    sound: "64IAMGHOSTOFFORMERSELF.mp3",
    text: "나는",
    synonym: "아득하다",
  },
  {
    soundNum: "65",
    sound: "65IAMQNOWAY.mp3",
    text: "내가",
    synonym: "내가 내가 내가",
  },
  {
    soundNum: "66",
    sound: "66IAMRESIGNED.mp3",
    text: "내가",
    synonym: "그들을 본다",
  },
  {
    soundNum: "67",
    sound: "67YOUARECONFESSUPPORT.mp3",
    text: "당신은",
    synonym: "나를 본다",
  },
  {
    soundNum: "68",
    sound: "68YOUAREDEF.mp3",
    text: "당신은",
    synonym: "두렵다",
  },
  {
    soundNum: "69",
    sound: "69YOUAREDEFWISEMIX.mp3",
    text: "당신은",
    synonym: "아무것도 갖고있지 않다",
  },
  {
    soundNum: "70",
    sound: "70NBDYSEESMESADCONFESLAMENT.mp3",
    text: "아무도 나를 보지 않는다",
    synonym: "",
  },
  {
    soundNum: "71",
    sound: "71NBDYSEESMESADGIRLZ.mp3",
    text: "아무도 나를 보지 않는다",
    synonym: "당신은 나를 본다",
  },
  {
    soundNum: "72",
    sound: "72NBDYSEESMEHAHA4SURE.mp3",
    text: "아무도 나를 보지 않는다",
    synonym: "이따금 나는 가버린다",
  },
  {
    soundNum: "73",
    sound: "73BEMEYOUTRY.mp3",
    text: "내가 되서",
    synonym: "안보여진다, 당신은",
  },
  {
    soundNum: "74",
    sound: "74BEMESOFTADMONISH.mp3",
    text: "내가 되서",
    synonym: "여기 있다",
  },
]

export default ko
