const es = [
  {
    soundNum: "1",
    sound: "001_sometimesiamwonder_chorus.mp3",
    text: "a veces yo soy",
    synonym: "invisible",
  },
  {
    soundNum: "2",
    sound: "002_sometimesiam_high.mp3",
    text: "a veces yo soy",
    synonym: "diferente",
  },
  {
    soundNum: "3",
    sound: "003_sometimesiam_wonder_low.mp3",
    text: "a veces yo soy",
    synonym: "ausente",
  },
  {
    soundNum: "4",
    sound: "004_sometimesiam_definite_high.mp3",
    text: "a veces yo soy",
    synonym: "nada",
  },
  {
    soundNum: "5",
    sound: "005_sometimesiam_definite_lowslow.mp3",
    text: "a veces yo soy",
    synonym: "no vista",
  },
  {
    soundNum: "6",
    sound: "006_sometimesiam_definite_mix.mp3",
    text: "a veces yo soy",
    synonym: "perdida",
  },
  {
    soundNum: "7",
    sound: "007_weare_def_mix.mp3",
    text: "somos",
    synonym: "ausente",
  },
  {
    soundNum: "8",
    sound: "008_theyare_high whatever.mp3",
    text: "ellos son",
    synonym: "escondidos",
  },
  {
    soundNum: "9",
    sound: "009_theyarelowaccuse.mp3",
    text: "ellos son",
    synonym: "perdidos",
  },
  {
    soundNum: "10",
    sound: "010_wecan_defmix.mp3",
    text: "podemos",
    synonym: "desaparecer",
  },
  {
    soundNum: "11",
    sound: "011_wecan_realy_mix.mp3",
    text: "podemos",
    synonym: "pretender",
  },
  {
    soundNum: "12",
    sound: "012_theycan.mp3",
    text: "ellos pueden",
    synonym: "",
  },
  {
    soundNum: "13",
    sound: "013_theycan_high_def.mp3",
    text: "ellos pueden",
    synonym: "ser invisibles",
  },
  {
    soundNum: "14",
    sound: "014_wecant_group_plaint.mp3",
    text: "no podemos",
    synonym: "",
  },
  {
    soundNum: "15",
    sound: "015_wecant_low.mp3",
    text: "no podemos",
    synonym: "ser distantes",
  },
  {
    soundNum: "16",
    sound: "016_youare_group.mp3",
    text: "vos sos",
    synonym: "ser vistos",
  },
  {
    soundNum: "17",
    sound: "017_youare_lowslow.mp3",
    text: "vos sos",
    synonym: "ausente",
  },
  {
    soundNum: "18",
    sound: "018_youare_accuse.mp3",
    text: "sos vos",
    synonym: "diferente",
  },
  {
    soundNum: "19",
    sound: "019_youare.mp3",
    text: "vos sos",
    synonym: "invisible",
  },
  {
    soundNum: "20",
    sound: "020_youare_accuse.mp3",
    text: "sos vos",
    synonym: "",
  },
  {
    soundNum: "21",
    sound: "021_youare_group.mp3",
    text: "sos vos",
    synonym: "diferente",
  },
  {
    soundNum: "22",
    sound: "022_youare_accuse.mp3",
    text: "sos vos",
    synonym: "distante",
  },
  {
    soundNum: "23",
    sound: "023_beyou_ss.mp3",
    text: "sé vos",
    synonym: "",
  },
  {
    soundNum: "24",
    sound: "024_bethem.mp3",
    text: "sé ellos",
    synonym: "perdidas",
  },
  {
    soundNum: "25",
    sound: "025_bethem_family.mp3",
    text: "sé ellos",
    synonym: "solos",
  },
  {
    soundNum: "26",
    sound: "026_invisible_dbl.mp3",
    text: "invisible",
    synonym: "escondido",
  },
  {
    soundNum: "27",
    sound: "027_invisible.mp3",
    text: "invisible",
    synonym: "perdida",
  },
  {
    soundNum: "28",
    sound: "028_invisible_ghost.mp3",
    text: "invisible",
    synonym: "perdides",
  },
  {
    soundNum: "29",
    sound: "029_invisible_multi.mp3",
    text: "invisible",
    synonym: "distantes",
  },
  {
    soundNum: "30",
    sound: "030_invisible_accuse.mp3",
    text: "invisible",
    synonym: "inexistentes",
  },
  {
    soundNum: "31",
    sound: "031_invisible_lost.mp3",
    text: "invisible",
    synonym: "miedosas",
  },
  {
    soundNum: "32",
    sound: "032_invisible_accuse.mp3",
    text: "invisible",
    synonym: "",
  },
  {
    soundNum: "33",
    sound: "033_seethem_ss.mp3",
    text: "véanme",
    synonym: "pequeñas",
  },
  {
    soundNum: "34",
    sound: "034_seethem_chant.mp3",
    text: "véanme",
    synonym: "visible",
  },
  {
    soundNum: "35",
    sound: "035_seethem_gang.mp3",
    text: "vélos",
    synonym: "perdidos",
  },
  {
    soundNum: "36",
    sound: "036_seeme_insist.mp3",
    text: "véanme",
    synonym: "fuerte",
  },
  {
    soundNum: "37",
    sound: "037_seeme_ss.mp3",
    text: "véanme",
    synonym: "libre",
  },
  {
    soundNum: "38",
    sound: "038_seeme_insist.mp3",
    text: "véanme",
    synonym: "triste",
  },
  {
    soundNum: "39",
    sound: "039_sometimesiam_qu.mp3",
    text: "a veces yo soy",
    synonym: "miedosa",
  },
  {
    soundNum: "40",
    sound: "040_sometimesiam_def.mp3",
    text: "a veces yo soy",
    synonym: "contente",
  },
  {
    soundNum: "41",
    sound: "041_sometimesiam_mix.mp3",
    text: "a veces yo soy",
    synonym: "visible",
  },
  {
    soundNum: "42",
    sound: "042_seeyou_ss.mp3",
    text: "te Veo",
    synonym: "pequeña",
  },
  {
    soundNum: "43",
    sound: "043_seeyou_trio.mp3",
    text: "te Veo",
    synonym: "inexistente",
  },
  {
    soundNum: "44",
    sound: "044_seeyou_accuse.mp3",
    text: "te Veo",
    synonym: "lejana",
  },
  {
    soundNum: "45",
    sound: "045_seeyou_accuse.mp3",
    text: "te Veo",
    synonym: "libre",
  },
  {
    soundNum: "46",
    sound: "046_theyare_qu.mp3",
    text: "ellos estan",
    synonym: "miedosos",
  },
  {
    soundNum: "47",
    sound: "047_theyareaccuse.mp3",
    text: "ellos estan",
    synonym: "inexistentes",
  },
  {
    soundNum: "48",
    sound: "048_seethem_accusegroup.mp3",
    text: "vélos",
    synonym: "libres",
  },
  {
    soundNum: "49",
    sound: "049_seethem_accuse.mp3",
    text: "vélos",
    synonym: "visibles",
  },
  {
    soundNum: "50",
    sound: "050_seethemfurtive.mp3",
    text: "vélos",
    synonym: "tristes",
  },
  {
    soundNum: "51",
    sound: "051_youcant_multi.mp3",
    text: "vos no podes",
    synonym: "pretender",
  },
  {
    soundNum: "52",
    sound: "051_youcant_multi.mp3",
    text: "vos no podes",
    synonym: "ser diferente",
  },
  {
    soundNum: "53",
    sound: "053_youcant_insist.mp3",
    text: "vos no podes",
    synonym: "pretender",
  },
  {
    soundNum: "54",
    sound: "054_youcant_insistsolo.mp3",
    text: "vos no podes",
    synonym: "verme",
  },
  {
    soundNum: "55",
    sound: "055_theycant_nohope.mp3",
    text: "ellos no pueden",
    synonym: "ser distantes",
  },
  {
    soundNum: "56",
    sound: "056_theycant_insist.mp3",
    text: "ellos no pueden",
    synonym: "ser diferentes",
  },
  {
    soundNum: "57",
    sound: "057_iam_sure.mp3",
    text: "yo soy",
    synonym: "diferente",
  },
  {
    soundNum: "58",
    sound: "058_iam_qu.mp3",
    text: "yo soy",
    synonym: "distante",
  },
  {
    soundNum: "59",
    sound: "059_youcant_seeme.mp3",
    text: "vos no podes",
    synonym: "estar ausente",
  },
  {
    soundNum: "60",
    sound: "060_youcantseeme_insist.mp3",
    text: "vos no podes",
    synonym: "ser diferente",
  },
  {
    soundNum: "61",
    sound: "061_youcant_seeme_insist.mp3",
    text: "vos no podes",
    synonym: "estar perdida",
  },
  {
    soundNum: "62",
    sound: "062_youcant_seeme_insist.mp3",
    text: "vos no podes",
    synonym: "estar distantes",
  },
  {
    soundNum: "63",
    sound: "063_iam_calm.mp3",
    text: "yo soy",
    synonym: "alegre",
  },
  {
    soundNum: "64",
    sound: "064_iam_group.mp3",
    text: "yo soy",
    synonym: "confidente",
  },
  {
    soundNum: "65",
    sound: "065_iam_solo.mp3",
    text: "yo soy",
    synonym: "distante",
  },
  {
    soundNum: "66",
    sound: "066_iam_mix.mp3",
    text: "yo soy",
    synonym: "vos sos",
  },
  {
    soundNum: "67",
    sound: "067_iam_insist.mp3",
    text: "yo soy",
    synonym: "testaruda",
  },
  {
    soundNum: "68",
    sound: "068_youare_insist.mp3",
    text: "vos sos",
    synonym: "",
  },
  {
    soundNum: "69",
    sound: "069_youare_insist.mp3",
    text: "vos sos",
    synonym: "cruel",
  },
  {
    soundNum: "70",
    sound: "070_nobodyseesme_mix.mp3",
    text: "nadie me ve",
    synonym: "distante",
  },
  {
    soundNum: "71",
    sound: "071_nobodyseesme_insist.mp3",
    text: "nadie me ve",
    synonym: "sola",
  },
  {
    soundNum: "72",
    sound: "072_beme_ss.mp3",
    text: "sé yo",
    synonym: "ahora",
  },
  {
    soundNum: "73",
    sound: "073_beme_insist.mp3",
    text: "sé yo",
    synonym: "momentaneamente",
  },
  {
    soundNum: "74",
    sound: "074_beme_ groupmix.mp3",
    text: "sé yo",
    synonym: "",
  },
]

export default es
