const en = [
  {
    soundNum: 1,
    sound: "sound-001.mp3",
    text: "you are",
    synonym: "different",
  },
  {
    soundNum: 2,
    sound: "sound-002.mp3",
    text: "they can't",
    synonym: "won't",
  },
  {
    soundNum: 3,
    sound: "sound-003.mp3",
    text: "see you",
    synonym: "hidden",
  },
  {
    soundNum: 4,
    sound: "sound-004.mp3",
    text: "i can't",
    synonym: "you won't",
  },
  {
    soundNum: 5,
    sound: "sound-005.mp3",
    text: "be them",
    synonym: "different",
  },
  {
    soundNum: 6,
    sound: "sound-006.mp3",
    text: "be them",
    synonym: "unseen",
  },
  {
    soundNum: 7,
    sound: "sound-007.mp3",
    text: "sometimes i am",
    synonym: "invisible",
  },
  {
    soundNum: 8,
    sound: "sound-008.mp3",
    text: "i am",
    synonym: "lost",
  },
  {
    soundNum: 9,
    sound: "sound-009.mp3",
    text: "you are",
    synonym: "they are",
  },
  {
    soundNum: 10,
    sound: "sound-010.mp3",
    text: "i am",
    synonym: "gone",
  },
  {
    soundNum: 11,
    sound: "sound-011.mp3",
    text: "be you",
    synonym: "pretend",
  },
  {
    soundNum: 12,
    sound: "sound-012.mp3",
    text: "invisible",
    synonym: "",
  },
  {
    soundNum: 13,
    sound: "sound-013.mp3",
    text: "i can't",
    synonym: "you won't",
  },
  {
    soundNum: 14,
    sound: "sound-014.mp3",
    text: "see me",
    synonym: "see you",
  },
  {
    soundNum: 15,
    sound: "sound-015.mp3",
    text: "sometimes they are",
    synonym: "invisible",
  },
  {
    soundNum: 16,
    sound: "sound-016.mp3",
    text: "i am",
    synonym: "absent",
  },
  {
    soundNum: 17,
    sound: "sound-017.mp3",
    text: "invisible",
    synonym: "",
  },
  {
    soundNum: 18,
    sound: "sound-018.mp3",
    text: "be them",
    synonym: "I can't",
  },
  {
    soundNum: 19,
    sound: "sound-019.mp3",
    text: "you are",
    synonym: "different",
  },
  {
    soundNum: 20,
    sound: "sound-020.mp3",
    text: "i can't",
    synonym: "missing",
  },
  {
    soundNum: 21,
    sound: "sound-021.mp3",
    text: "be you",
    synonym: "different",
  },
  {
    soundNum: 22,
    sound: "sound-022.mp3",
    text: "sometimes",
    synonym: "",
  },
  {
    soundNum: 23,
    sound: "sound-023.mp3",
    text: "see them",
    synonym: "missing",
  },
  {
    soundNum: 24,
    sound: "sound-024.mp3",
    text: "you can't",
    synonym: "be me",
  },
  {
    soundNum: 25,
    sound: "sound-025.mp3",
    text: "they are",
    synonym: "different",
  },
  {
    soundNum: 26,
    sound: "sound-026.mp3",
    text: "i am",
    synonym: "invisible",
  },
  {
    soundNum: 27,
    sound: "sound-027.mp3",
    text: "sometimes i am",
    synonym: "distant",
  },
  {
    soundNum: 28,
    sound: "sound-028.mp3",
    text: "invisible",
    synonym: "",
  },
  {
    soundNum: 29,
    sound: "sound-029.mp3",
    text: "i can't",
    synonym: "alone",
  },
  {
    soundNum: 30,
    sound: "sound-030.mp3",
    text: "you can't",
    synonym: "see me",
  },
  {
    soundNum: 31,
    sound: "sound-031.mp3",
    text: "see them",
    synonym: "different",
  },
  {
    soundNum: 32,
    sound: "sound-032.mp3",
    text: "sometimes i am invisible",
    synonym: "",
  },
  {
    soundNum: 33,
    sound: "sound-033.mp3",
    text: "sometimes i am",
    synonym: "",
  },
  {
    soundNum: 34,
    sound: "sound-034.mp3",
    text: "you are",
    synonym: "not here",
  },
  {
    soundNum: 35,
    sound: "sound-035.mp3",
    text: "see you",
    synonym: "invisible",
  },
  {
    soundNum: 36,
    sound: "sound-036.mp3",
    text: "invisible",
    synonym: "",
  },
  {
    soundNum: 37,
    sound: "sound-037.mp3",
    text: "see you",
    synonym: "gone",
  },
  {
    soundNum: 38,
    sound: "sound-038.mp3",
    text: "invisible",
    synonym: "",
  },
  {
    soundNum: 39,
    sound: "sound-039.mp3",
    text: "they can't",
    synonym: "see me",
  },
  {
    soundNum: 40,
    sound: "sound-040.mp3",
    text: "sometimes",
    synonym: "",
  },
  {
    soundNum: 41,
    sound: "sound-041.mp3",
    text: "sometimes",
    synonym: "you are",
  },
  {
    soundNum: 42,
    sound: "sound-042.mp3",
    text: "sometimes",
    synonym: "unseen",
  },
  {
    soundNum: 43,
    sound: "sound-043.mp3",
    text: "invisible",
    synonym: "",
  },
  {
    soundNum: 44,
    sound: "sound-044.mp3",
    text: "invisible",
    synonym: "",
  },
  {
    soundNum: 45,
    sound: "sound-045.mp3",
    text: "i am",
    synonym: "gone",
  },
  {
    soundNum: 46,
    sound: "sound-046.mp3",
    text: "you can't",
    synonym: "won't",
  },
  {
    soundNum: 47,
    sound: "sound-047.mp3",
    text: "invisible",
    synonym: "",
  },
  {
    soundNum: 48,
    sound: "sound-048.mp3",
    text: "you are",
    synonym: "distant",
  },
  {
    soundNum: 49,
    sound: "sound-049.mp3",
    text: "see them",
    synonym: "invisible",
  },
  {
    soundNum: 50,
    sound: "sound-050.mp3",
    text: "i am",
    synonym: "alone",
  },
  {
    soundNum: 51,
    sound: "sound-051.mp3",
    text: "be them",
    synonym: "disappear",
  },
  {
    soundNum: 52,
    sound: "sound-052.mp3",
    text: "we can't",
    synonym: "without",
  },
  {
    soundNum: 53,
    sound: "sound-053.mp3",
    text: "sometimes",
    synonym: "i am",
  },
  {
    soundNum: 54,
    sound: "sound-054.mp3",
    text: "sometimes they are",
    synonym: "invisible",
  },
  {
    soundNum: 55,
    sound: "sound-055.mp3",
    text: "invisible",
    synonym: "",
  },
  {
    soundNum: 56,
    sound: "sound-056.mp3",
    text: "sometimes i am",
    synonym: "alone",
  },
]

export default en
